//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardHistories
    {
        public long Id { get; set; }
        public int ExpectedWaitingTimeCount { get; set; }
        public int WaitedQueueCount { get; set; }
        public int LongerWaitedTime { get; set; }
        public int AvailAgenCount { get; set; }
        public int SkillNo { get; set; }
        public System.DateTime ProcessingTime { get; set; }
    }
}
