//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenpaDashboardEntities : DbContext
    {
        public GenpaDashboardEntities()
            : base("name=GenpaDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DashboardHistories> DashboardHistories { get; set; }
        public DbSet<DashboardSettings> DashboardSettings { get; set; }
        public DbSet<GeneralConfig> GeneralConfig { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<MailSettings> MailSettings { get; set; }
        public DbSet<SettingLogs> SettingLogs { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
