//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSettings
    {
        public int Id { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public Nullable<bool> SSL { get; set; }
        public Nullable<bool> UseDefaultCredental { get; set; }
        public string CredentalEmail { get; set; }
        public string CredentalPassword { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
