//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingLogs
    {
        public int Id { get; set; }
        public string MailServer { get; set; }
        public string MailReceiver { get; set; }
        public string ProcessResult { get; set; }
        public string MailPort { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
