//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashGen.GenpaDashboardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CmsParameters", Namespace="http://schemas.datacontract.org/2004/07/EmpCMSGetData")]
    [System.SerializableAttribute()]
    public partial class CmsParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcdNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkillNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcdNo {
            get {
                return this.AcdNoField;
            }
            set {
                if ((this.AcdNoField.Equals(value) != true)) {
                    this.AcdNoField = value;
                    this.RaisePropertyChanged("AcdNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkillNo {
            get {
                return this.SkillNoField;
            }
            set {
                if ((this.SkillNoField.Equals(value) != true)) {
                    this.SkillNoField = value;
                    this.RaisePropertyChanged("SkillNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealTimeReportType1", Namespace="http://schemas.datacontract.org/2004/07/EmpCMSGetData.CmsService")]
    [System.SerializableAttribute()]
    public partial class RealTimeReportType1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbandoneCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AchtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentsInAcwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentsInAuxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentsInCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnsweredCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AverageAcdTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AverageSpeedOfAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EwtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldestCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffAgentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbandoneCalls {
            get {
                return this.AbandoneCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AbandoneCallsField, value) != true)) {
                    this.AbandoneCallsField = value;
                    this.RaisePropertyChanged("AbandoneCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acht {
            get {
                return this.AchtField;
            }
            set {
                if ((object.ReferenceEquals(this.AchtField, value) != true)) {
                    this.AchtField = value;
                    this.RaisePropertyChanged("Acht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentsInAcw {
            get {
                return this.AgentsInAcwField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentsInAcwField, value) != true)) {
                    this.AgentsInAcwField = value;
                    this.RaisePropertyChanged("AgentsInAcw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentsInAux {
            get {
                return this.AgentsInAuxField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentsInAuxField, value) != true)) {
                    this.AgentsInAuxField = value;
                    this.RaisePropertyChanged("AgentsInAux");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentsInCall {
            get {
                return this.AgentsInCallField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentsInCallField, value) != true)) {
                    this.AgentsInCallField = value;
                    this.RaisePropertyChanged("AgentsInCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnsweredCalls {
            get {
                return this.AnsweredCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnsweredCallsField, value) != true)) {
                    this.AnsweredCallsField = value;
                    this.RaisePropertyChanged("AnsweredCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avail {
            get {
                return this.AvailField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailField, value) != true)) {
                    this.AvailField = value;
                    this.RaisePropertyChanged("Avail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AverageAcdTime {
            get {
                return this.AverageAcdTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AverageAcdTimeField, value) != true)) {
                    this.AverageAcdTimeField = value;
                    this.RaisePropertyChanged("AverageAcdTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AverageSpeedOfAnswer {
            get {
                return this.AverageSpeedOfAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AverageSpeedOfAnswerField, value) != true)) {
                    this.AverageSpeedOfAnswerField = value;
                    this.RaisePropertyChanged("AverageSpeedOfAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ewt {
            get {
                return this.EwtField;
            }
            set {
                if ((object.ReferenceEquals(this.EwtField, value) != true)) {
                    this.EwtField = value;
                    this.RaisePropertyChanged("Ewt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldestCall {
            get {
                return this.OldestCallField;
            }
            set {
                if ((object.ReferenceEquals(this.OldestCallField, value) != true)) {
                    this.OldestCallField = value;
                    this.RaisePropertyChanged("OldestCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other {
            get {
                return this.OtherField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherField, value) != true)) {
                    this.OtherField = value;
                    this.RaisePropertyChanged("Other");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Queue {
            get {
                return this.QueueField;
            }
            set {
                if ((object.ReferenceEquals(this.QueueField, value) != true)) {
                    this.QueueField = value;
                    this.RaisePropertyChanged("Queue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RingTime {
            get {
                return this.RingTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RingTimeField, value) != true)) {
                    this.RingTimeField = value;
                    this.RaisePropertyChanged("RingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sl {
            get {
                return this.SlField;
            }
            set {
                if ((object.ReferenceEquals(this.SlField, value) != true)) {
                    this.SlField = value;
                    this.RaisePropertyChanged("Sl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffAgent {
            get {
                return this.StaffAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffAgentField, value) != true)) {
                    this.StaffAgentField = value;
                    this.RaisePropertyChanged("StaffAgent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealTimeReportType2", Namespace="http://schemas.datacontract.org/2004/07/EmpCMSGetData.CmsService")]
    [System.SerializableAttribute()]
    public partial class RealTimeReportType2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbandoneCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcdCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuxTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateDurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbandoneCalls {
            get {
                return this.AbandoneCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AbandoneCallsField, value) != true)) {
                    this.AbandoneCallsField = value;
                    this.RaisePropertyChanged("AbandoneCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcdCalls {
            get {
                return this.AcdCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AcdCallsField, value) != true)) {
                    this.AcdCallsField = value;
                    this.RaisePropertyChanged("AcdCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIDField, value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentName {
            get {
                return this.AgentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNameField, value) != true)) {
                    this.AgentNameField = value;
                    this.RaisePropertyChanged("AgentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuxType {
            get {
                return this.AuxTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuxTypeField, value) != true)) {
                    this.AuxTypeField = value;
                    this.RaisePropertyChanged("AuxType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RingTime {
            get {
                return this.RingTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RingTimeField, value) != true)) {
                    this.RingTimeField = value;
                    this.RaisePropertyChanged("RingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillNo {
            get {
                return this.SkillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillNoField, value) != true)) {
                    this.SkillNoField = value;
                    this.RaisePropertyChanged("SkillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDuration {
            get {
                return this.StateDurationField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDurationField, value) != true)) {
                    this.StateDurationField = value;
                    this.RaisePropertyChanged("StateDuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealTimeReportType3", Namespace="http://schemas.datacontract.org/2004/07/EmpCMSGetData.CmsService")]
    [System.SerializableAttribute()]
    public partial class RealTimeReportType3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbandoneCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcdCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuxTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateDurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbandoneCalls {
            get {
                return this.AbandoneCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AbandoneCallsField, value) != true)) {
                    this.AbandoneCallsField = value;
                    this.RaisePropertyChanged("AbandoneCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcdCalls {
            get {
                return this.AcdCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AcdCallsField, value) != true)) {
                    this.AcdCallsField = value;
                    this.RaisePropertyChanged("AcdCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIDField, value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentName {
            get {
                return this.AgentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNameField, value) != true)) {
                    this.AgentNameField = value;
                    this.RaisePropertyChanged("AgentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuxType {
            get {
                return this.AuxTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuxTypeField, value) != true)) {
                    this.AuxTypeField = value;
                    this.RaisePropertyChanged("AuxType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RingTime {
            get {
                return this.RingTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RingTimeField, value) != true)) {
                    this.RingTimeField = value;
                    this.RaisePropertyChanged("RingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillNo {
            get {
                return this.SkillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillNoField, value) != true)) {
                    this.SkillNoField = value;
                    this.RaisePropertyChanged("SkillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDuration {
            get {
                return this.StateDurationField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDurationField, value) != true)) {
                    this.StateDurationField = value;
                    this.RaisePropertyChanged("StateDuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoricalReportType1", Namespace="http://schemas.datacontract.org/2004/07/EmpCMSGetData.CmsService")]
    [System.SerializableAttribute()]
    public partial class HistoricalReportType1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbandoneCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnsweredCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AverageAcdTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AverageSpeedOfAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbandoneCalls {
            get {
                return this.AbandoneCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AbandoneCallsField, value) != true)) {
                    this.AbandoneCallsField = value;
                    this.RaisePropertyChanged("AbandoneCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnsweredCalls {
            get {
                return this.AnsweredCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnsweredCallsField, value) != true)) {
                    this.AnsweredCallsField = value;
                    this.RaisePropertyChanged("AnsweredCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AverageAcdTime {
            get {
                return this.AverageAcdTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AverageAcdTimeField, value) != true)) {
                    this.AverageAcdTimeField = value;
                    this.RaisePropertyChanged("AverageAcdTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AverageSpeedOfAnswer {
            get {
                return this.AverageSpeedOfAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AverageSpeedOfAnswerField, value) != true)) {
                    this.AverageSpeedOfAnswerField = value;
                    this.RaisePropertyChanged("AverageSpeedOfAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RingTime {
            get {
                return this.RingTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RingTimeField, value) != true)) {
                    this.RingTimeField = value;
                    this.RaisePropertyChanged("RingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sl {
            get {
                return this.SlField;
            }
            set {
                if ((object.ReferenceEquals(this.SlField, value) != true)) {
                    this.SlField = value;
                    this.RaisePropertyChanged("Sl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenpaDashboardService.ICmsData")]
    public interface ICmsData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetRealTimeReportType1", ReplyAction="http://tempuri.org/ICmsData/GetRealTimeReportType1Response")]
        DashGen.GenpaDashboardService.RealTimeReportType1 GetRealTimeReportType1(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetRealTimeReportType1", ReplyAction="http://tempuri.org/ICmsData/GetRealTimeReportType1Response")]
        System.Threading.Tasks.Task<DashGen.GenpaDashboardService.RealTimeReportType1> GetRealTimeReportType1Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetRealTimeReportType2", ReplyAction="http://tempuri.org/ICmsData/GetRealTimeReportType2Response")]
        DashGen.GenpaDashboardService.RealTimeReportType2[] GetRealTimeReportType2(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetRealTimeReportType2", ReplyAction="http://tempuri.org/ICmsData/GetRealTimeReportType2Response")]
        System.Threading.Tasks.Task<DashGen.GenpaDashboardService.RealTimeReportType2[]> GetRealTimeReportType2Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetRealTimeReportType3", ReplyAction="http://tempuri.org/ICmsData/GetRealTimeReportType3Response")]
        DashGen.GenpaDashboardService.RealTimeReportType3[] GetRealTimeReportType3(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetRealTimeReportType3", ReplyAction="http://tempuri.org/ICmsData/GetRealTimeReportType3Response")]
        System.Threading.Tasks.Task<DashGen.GenpaDashboardService.RealTimeReportType3[]> GetRealTimeReportType3Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetHistoricalReportType1", ReplyAction="http://tempuri.org/ICmsData/GetHistoricalReportType1Response")]
        DashGen.GenpaDashboardService.HistoricalReportType1 GetHistoricalReportType1(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICmsData/GetHistoricalReportType1", ReplyAction="http://tempuri.org/ICmsData/GetHistoricalReportType1Response")]
        System.Threading.Tasks.Task<DashGen.GenpaDashboardService.HistoricalReportType1> GetHistoricalReportType1Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICmsDataChannel : DashGen.GenpaDashboardService.ICmsData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CmsDataClient : System.ServiceModel.ClientBase<DashGen.GenpaDashboardService.ICmsData>, DashGen.GenpaDashboardService.ICmsData {
        
        public CmsDataClient() {
        }
        
        public CmsDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CmsDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CmsDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CmsDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DashGen.GenpaDashboardService.RealTimeReportType1 GetRealTimeReportType1(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetRealTimeReportType1(cmsParameters);
        }
        
        public System.Threading.Tasks.Task<DashGen.GenpaDashboardService.RealTimeReportType1> GetRealTimeReportType1Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetRealTimeReportType1Async(cmsParameters);
        }
        
        public DashGen.GenpaDashboardService.RealTimeReportType2[] GetRealTimeReportType2(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetRealTimeReportType2(cmsParameters);
        }
        
        public System.Threading.Tasks.Task<DashGen.GenpaDashboardService.RealTimeReportType2[]> GetRealTimeReportType2Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetRealTimeReportType2Async(cmsParameters);
        }
        
        public DashGen.GenpaDashboardService.RealTimeReportType3[] GetRealTimeReportType3(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetRealTimeReportType3(cmsParameters);
        }
        
        public System.Threading.Tasks.Task<DashGen.GenpaDashboardService.RealTimeReportType3[]> GetRealTimeReportType3Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetRealTimeReportType3Async(cmsParameters);
        }
        
        public DashGen.GenpaDashboardService.HistoricalReportType1 GetHistoricalReportType1(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetHistoricalReportType1(cmsParameters);
        }
        
        public System.Threading.Tasks.Task<DashGen.GenpaDashboardService.HistoricalReportType1> GetHistoricalReportType1Async(DashGen.GenpaDashboardService.CmsParameters cmsParameters) {
            return base.Channel.GetHistoricalReportType1Async(cmsParameters);
        }
    }
}
